**1.Write a Python Program to Add Two Matrices?**

In [40]:
import numpy as np

mat1=np.arange(8).reshape(2,4)
mat2=np.random.randint(1,17,8).reshape(2,4)
print(mat1)
print()
print(mat2)
print()

print(np.add(mat1,mat2))

[[0 1 2 3]
 [4 5 6 7]]

[[ 8 12  1  5]
 [15  6 13  9]]

[[ 8 13  3  8]
 [19 11 19 16]]


**2.Write a Python Program to Multiply Two Matrices?**

In [41]:
# using above matrices

print(np.multiply(mat1,mat2))

[[ 0 12  2 15]
 [60 30 78 63]]



**3.Write a Python Program to Transpose a Matrix?**

In [42]:
print(mat1.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]



**4.Write a Python Program to Sort Words in Alphabetic Order?**

In [44]:
l=['shivansh','ajay','rahul','bittu','bablu']
print(sorted(l))

['ajay', 'bablu', 'bittu', 'rahul', 'shivansh']


**5.Write a Python Program to Remove Punctuation From a String?**

In [53]:
s='Hello my name is shivansh, i am 29 years old. I live in dehradun, and i am learning data sciece/machine learning from ineuron!'

''.join(s.split(','))

'Hello my name is shivansh i am 29 years old. I live in dehradun and i am learning data sciece/machine learning from ineuron!'